import React from "react"
import { IconTv } from "../ui/icons/IconTv"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconTv,
  "https://www.figma.com/design/H8Bja8G8LT0f8UxS4vg00P?node-id=4049%3A13648",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        "16": "16",
        "20": "20",
        "24": "24",
        "32": "32",
        "40": "40",
        "48": "48",
      }),
    },
    example: (props) => <IconTv size={props.size} />,
  },
)
