import React from "react"
import { Table } from "../ui/primitives/Table/Table"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Table,
  "https://www.figma.com/design/H8Bja8G8LT0f8UxS4vg00P?node-id=4049%3A13630",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "size": figma.enum('Size', {
      //   "20": "20",
      //   "24": "24",
      //   "32": "32",
      //   "40": "40",
      //   "48": "48",
      //   "16": "16"
      // })
    },
    example: (props) => <Table />,
  },
)
